name: Validating Build Steps
on:
  push:
    branches:
      - main # Replace with your default branch name if it's not "main"

jobs:
  tests:
    name: Start Validating
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0' # Use the version of Node.js that you're using in your project

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run Svelte Check
        run: npm run check

      - name: Run Unit Tests
        run: npm run test:unit

      - name: Run Integration Tests
        run: npm run test:integration

      - name: Run Page Performance
        run: |
          npm install -g @lhci/cli@0.12.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"

      - name: Build Project
        run: npm run build
